# Practicing Numpy

In [1]:
import numpy as np
import pandas as pd

In [2]:
l = [1,2,3,4,5]
a= np.array(l)
print(a)

[1 2 3 4 5]


In [3]:
print(a+10)

[11 12 13 14 15]


In [4]:
a.ndim

1

In [5]:
a.shape

(5,)

In [7]:
a.tolist()

[1, 2, 3, 4, 5]

In [16]:
a[0]=2
print(a)
a[0]=15

[ 2 19 24 32 37 42 46]


In [4]:
l=[15,19,24,32,37,42,46]

a=np.array(l)

print(a)

[15 19 24 32 37 42 46]


In [10]:
a[2]

np.int64(24)

In [11]:
print(a[-2])

42


In [12]:
a[1:6:1]

array([19, 24, 32, 37, 42])

In [13]:
a[:3]

array([15, 19, 24])

In [14]:
a[[0,2,4,5]]

array([15, 24, 37, 42])

In [15]:
a[a>40]

array([42, 46])

In [17]:
a%2==0

array([False, False,  True,  True, False,  True,  True])

In [16]:
a[a%2==0]

array([24, 32, 42, 46])

In [4]:
a[(a>30) & (a<40)]

array([32, 37])

In [5]:
(a>30) & (a<40)

array([False, False, False,  True,  True, False, False])

# Data Manipulation or Data Modification
- Insert | Update | Delete 

In [6]:
print(a)

[15 19 24 32 37 42 46]


In [7]:
np.append(a,50)

array([15, 19, 24, 32, 37, 42, 46, 50])

In [8]:
a1 = np.append(a,60)
print(a1)

[15 19 24 32 37 42 46 60]


In [10]:
a2 = np.append(a,[70,80])
print(a2)

[15 19 24 32 37 42 46 70 80]


# Delete Operation

In [11]:
a3 = np.delete(a,1)
print(a3)

[15 24 32 37 42 46]


In [13]:
a4 = np.delete(a,[1,3])
print(a4)

[15 24 37 42 46]


In [18]:
b = np.array([23,44,55,76])
print(b)

[23 44 55 76]


In [19]:
b[-1]=77
print(b)

[23 44 55 77]


In [22]:
b[[0,-2]]=51
print(b)

[51 44 51 77]


In [27]:
b[[0,-2]]=51,69
print(b)

[51 44 69 77]


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [26]:
c=np.sort(b)
print(c)

[44 51 69 77]


In [28]:
d=b.copy()
print(id(b))
print(id(d))
print(d)

2217960155120
2217975385808
[51 44 69 77]


In [29]:
print(d**2)

[2601 1936 4761 5929]


In [30]:
print(b+d)

[102  88 138 154]


In [31]:
print(d-b)

[0 0 0 0]


# Practicing Pandas

In [12]:
mixList=[12,True,23.56,'ssw']
mixedArray1=np.array(mixList)
print(mixedArray1)
print(mixedArray1.shape)
print(mixedArray1.ndim)

['12' 'True' '23.56' 'ssw']
(4,)
1


In [5]:
print(l)

[15, 19, 24, 32, 37, 42, 46]


In [6]:
s = pd.Series(l)
print(s)

0    15
1    19
2    24
3    32
4    37
5    42
6    46
dtype: int64


In [7]:
s.ndim

1

In [8]:
s.shape

(7,)

In [2]:
np.random.randint(1,100,8)

array([15,  5, 68, 21, 34, 90, 70, 11], dtype=int32)